import SwiftUI
import Combine
import CryptoKit

@main
struct StickyApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    var body: some Scene {
        Settings { EmptyView() }
    }
}

@MainActor
final class AppDelegate: NSObject, NSApplicationDelegate {
    static var sharedViewModel: NotchViewModel?

    private var notchController: NotchWindowController?
    private let viewModel = NotchViewModel()
    private var discoveryService: DiscoveryService?
    private var transferService: TransferService?
    private var clipboardService: ClipboardService?
    private var controlService: ControlService?
    private let hapticService = HapticService()
    private let soundService = SoundService()
    private let recentsStore = RecentsStore()
    private let arrivalNotifier = ArrivalNotifier()
    private var statusItem: NSStatusItem?
    private var peerSubscription: AnyCancellable?
    private var stateSubscription: AnyCancellable?
    private var servicesAreRunning = false

    /// The batch this delegate handed to the view model and is still entitled to
    /// record as a recent. The view model owns the only success signal there is
    /// and exposes it as state, not as a callback, so the claim has to be
    /// staked before the send and released the moment the portal shows a
    /// different batch.
    /// Set once the portal is actually showing the claimed batch. An arriving
    /// transfer finishing lands on the same `.success` state as a send, so
    /// without this an inbound file could be credited to an outbound batch that
    /// never left.
    /// The completion callback carries a count and no sender, so the name is
    /// remembered from the offer that opened the same transfer.
    private var lastIncomingSenderName: String?

    private var pasteboardPoller: Timer?
    private var lastPasteboardChangeCount: Int = 0
    /// Fingerprint of the text the peer last sent us. Anything matching it is
    /// the peer's own clipboard coming back around, not a fresh local copy.
    private var lastRemoteClipboardFingerprint: String?

    /// Markers other apps use to say "do not sync/store this": password
    /// managers mark copies concealed, and transient/auto-generated copies are
    /// never meant to leave the machine.
    private static let clipboardOptOutTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    func applicationDidFinishLaunching(_ notification: Notification) {
        NSApp.setActivationPolicy(.accessory)
        Self.sharedViewModel = viewModel
        // Staged drops outlive a crash or a quit with the shelf still full;
        // launch is the one moment nothing is holding them.
        DropIntake.purgeStaleStagedDrops()
        startServices()
        installInterface()

        NSWorkspace.shared.notificationCenter.addObserver(
            self,
            selector: #selector(handleWake),
            name: NSWorkspace.didWakeNotification,
            object: nil
        )
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(handleScreenChange),
            name: NSApplication.didChangeScreenParametersNotification,
            object: nil
        )
    }

    func applicationShouldHandleReopen(_ sender: NSApplication, hasVisibleWindows flag: Bool) -> Bool {
        chooseFilesToSend()
        return true
    }

    func applicationWillTerminate(_ notification: Notification) {
        stopServices()
    }

    static func startPasteboardWatcherStatic() {
        (NSApp.delegate as? AppDelegate)?.startPasteboardWatcher()
    }

    private func startPasteboardWatcher() {
        guard pasteboardPoller == nil else { return }
        lastPasteboardChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 1.0, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                guard let self else { return }
                let pb = NSPasteboard.general
                guard self.viewModel.clipboardSyncEnabled,
                      pb.changeCount != self.lastPasteboardChangeCount else {
                    self.lastPasteboardChangeCount = pb.changeCount
                    return
                }
                self.lastPasteboardChangeCount = pb.changeCount
                let types = pb.types?.map(\.rawValue) ?? []
                guard !types.contains(where: { Self.clipboardOptOutTypes.contains($0) }) else { return }
                if let text = pb.string(forType: .string), !text.isEmpty {
                    let fingerprint = Self.clipboardFingerprint(for: text)
                    guard fingerprint != self.lastRemoteClipboardFingerprint else { return }
                    self.lastRemoteClipboardFingerprint = nil
                    self.viewModel.clipboardSyncSender?(text)
                }
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        pasteboardPoller = timer
    }

    private func stopPasteboardWatcher() {
        pasteboardPoller?.invalidate()
        pasteboardPoller = nil
    }

    private static func clipboardFingerprint(for text: String) -> String {
        SHA256.hash(data: Data(text.utf8)).map { String(format: "%02x", $0) }.joined()
    }

    private func startServices() {
        guard !servicesAreRunning else { return }

        let discovery = DiscoveryService(name: Host.current().localizedName ?? ProcessInfo.processInfo.hostName)
        let transfer = TransferService(discovery: discovery)
        let clipboard = ClipboardService()

        discoveryService = discovery
        transferService = transfer
        clipboardService = clipboard
        controlService = ControlService(discovery: discovery, transfer: transfer, clipboard: clipboard)
        controlService?.start()
        transfer.onFailure = { [weak self] message in
            Task { @MainActor in self?.controlService?.recordNativeError(message) }
        }
        peerSubscription = discovery.$peers
            .receive(on: DispatchQueue.main)
            .sink { [weak self] peers in
                guard let self else { return }
                let available = !peers.isEmpty
                self.viewModel.updatePeerAvailability(available)
                self.viewModel.peerName = peers.first?.name
                self.refreshPeerCount()
            }

        viewModel.configure(
            haptics: hapticService,
            sounds: soundService,
            transfer: transfer,
            clipboard: clipboard,
            clipboardSender: { [weak self] text in
                Task { @MainActor [weak self] in
                    await self?.sendClipboard(text)
                }
            },
            pairingCode: transfer.pairingCode,
            pairingCodeProvider: { [weak transfer] in transfer?.pairingCode ?? "------" },
            pairingAction: { [weak self] in self?.showPairingDialog() },
            unpairAllAction: { [weak self] in self?.forgetPairedDevices() }
        )
        soundService.prepare()

        stateSubscription = viewModel.$state
            .receive(on: DispatchQueue.main)
            .sink { [weak self] state in
            }

        transfer.onIncoming = { [weak self] sender, count, kind in
            Task { @MainActor [weak self] in
                self?.lastIncomingSenderName = sender
                self?.viewModel.receiveIncomingOffer(senderName: sender, fileCount: count, kind: kind)
            }
        }

        transfer.onClipboardReceived = { [weak self] text, senderName in
            Task { @MainActor [weak self] in
                guard let self else { return }
                self.viewModel.receiveRemoteClipboard(text, senderName: senderName)
                // Clipboard sync: received text also lands on the system clipboard.
                if self.viewModel.clipboardSyncEnabled {
                    NSPasteboard.general.clearContents()
                    NSPasteboard.general.setString(text, forType: .string)
                    // Writing bumps changeCount, so adopt it here — otherwise the
                    // poller reads the peer's own text back a second later and
                    // ships it home, looping forever between two Macs. The
                    // fingerprint covers the same text arriving by local re-copy.
                    self.lastPasteboardChangeCount = NSPasteboard.general.changeCount
                    self.lastRemoteClipboardFingerprint = Self.clipboardFingerprint(for: text)
                }
            }
        }

        if viewModel.clipboardSyncEnabled {
            startPasteboardWatcher()
        }
        viewModel.onClipboardSyncChanged = { [weak self] enabled in
            guard let self else { return }
            if enabled {
                self.startPasteboardWatcher()
            } else {
                self.stopPasteboardWatcher()
            }
        }
        // Recents are recorded where the send actually succeeds, so drops made
        // straight at the notch count too — not just menu-initiated sends.
        viewModel.onSendSucceeded = { [weak self] urls in
            Task { @MainActor [weak self] in self?.recentsStore.recordFiles(urls) }
        }

        viewModel.clipboardSyncSender = { [weak self] text in
            Task { @MainActor [weak self] in
                await self?.sendClipboard(text)
            }
        }

        transfer.onIncomingCompleted = { [weak self] count in
            Task { @MainActor [weak self] in
                guard let self else { return }
                self.viewModel.receiveIncomingCompleted(count: count)
                self.arrivalNotifier.announceArrival(senderName: self.lastIncomingSenderName, itemCount: count)
                self.lastIncomingSenderName = nil
            }
        }

        // Monitoring only records local text in Sticky's private history. Sending
        // is an explicit paper-plane action in that history, never a background
        // copy of the system clipboard.
        clipboard.start(onTextPushed: { _ in })

        servicesAreRunning = true
    }

    private func stopServices() {
        guard servicesAreRunning else { return }
        viewModel.prepareForQuit()
        stopPasteboardWatcher()
        clipboardService?.stop()
        controlService?.stop()
        controlService = nil
        transferService?.stop()
        discoveryService?.stop()
        peerSubscription?.cancel()
        peerSubscription = nil
        stateSubscription?.cancel()
        stateSubscription = nil
        servicesAreRunning = false
    }

    private func installInterface() {
        notchController = NotchWindowController(viewModel: viewModel)
        notchController?.install()
        installMenuBarItemIfNeeded()
    }

    private func installMenuBarItemIfNeeded() {
        // Sticky is one app with two entrances: the native notch and a normal,
        // dependable menu-bar item. The icon is never a second process/window.
        if statusItem == nil {
            setupMenu()
        }
        NSApp.servicesProvider = ServicesProvider()
        NSUpdateDynamicServices()
    }

    private func setupMenu() {
        let menu = NSMenu()

        let sendItem = NSMenuItem(title: "Send files…", action: #selector(chooseFilesToSend), keyEquivalent: "s")
        sendItem.keyEquivalentModifierMask = [.command, .shift]
        menu.addItem(sendItem)

        let peersItem = NSMenuItem(title: "No devices nearby", action: nil, keyEquivalent: "")
        peersItem.isEnabled = false
        peersItem.tag = MenuAction.peerCount.rawValue
        menu.addItem(peersItem)

        let pendingItem = NSMenuItem(title: "No pending transfers", action: nil, keyEquivalent: "")
        pendingItem.isEnabled = false
        pendingItem.tag = MenuAction.pendingCount.rawValue
        menu.addItem(pendingItem)

        menu.addItem(NSMenuItem(title: "Send pending now", action: #selector(sendPendingTransfers), keyEquivalent: "r"))
        menu.addItem(NSMenuItem(title: "Clear pending queue", action: #selector(clearPendingTransfers), keyEquivalent: ""))
        let shelfItem = NSMenuItem(title: "Open Shelf", action: #selector(showShelf), keyEquivalent: "e")
        shelfItem.keyEquivalentModifierMask = [.command, .shift]
        menu.addItem(shelfItem)
        menu.addItem(NSMenuItem(title: "Send copied text", action: #selector(sendCopiedText), keyEquivalent: "t"))
        let openReceivedItem = NSMenuItem(title: "Open received files", action: #selector(openReceivedFiles), keyEquivalent: "o")
        // The recents section is rebuilt below this item on every open, so it
        // needs a stable anchor rather than an index that shifts with the menu.
        openReceivedItem.tag = MenuAction.openReceived.rawValue
        menu.addItem(openReceivedItem)

        if let code = transferService?.pairingCode {
            let codeItem = NSMenuItem(title: "This Mac's pairing code: \(code)", action: nil, keyEquivalent: "")
            codeItem.isEnabled = false
            codeItem.tag = MenuAction.pairingCode.rawValue
            menu.addItem(codeItem)
        }
        menu.delegate = self
        menu.addItem(NSMenuItem(title: "Pair a device…", action: #selector(showPairingDialog), keyEquivalent: ""))

        menu.addItem(.separator())
        menu.addItem(NSMenuItem(title: "Quit Sticky", action: #selector(quit), keyEquivalent: "q"))

        statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
        if let button = statusItem?.button {
            let dropArea = StatusBarDropArea(frame: .zero)
            dropArea.onFilesDropped = { [weak self] urls in
                Task { @MainActor [weak self] in
                    self?.sendFilesRecordingRecent(urls)
                }
            }
            dropArea.translatesAutoresizingMaskIntoConstraints = false
            button.addSubview(dropArea)
            NSLayoutConstraint.activate([
                dropArea.leadingAnchor.constraint(equalTo: button.leadingAnchor),
                dropArea.trailingAnchor.constraint(equalTo: button.trailingAnchor),
                dropArea.topAnchor.constraint(equalTo: button.topAnchor),
                dropArea.bottomAnchor.constraint(equalTo: button.bottomAnchor)
            ])
            button.image = NSImage(systemSymbolName: "arrow.up.arrow.down.circle", accessibilityDescription: "Sticky — drag files here or click for menu")
        }
        statusItem?.menu = menu
        refreshPeerCount()
        viewModel.updatePeerAvailability(!(discoveryService?.peers.isEmpty ?? true))
    }

    private func refreshPeerCount() {
        guard let menu = statusItem?.menu,
              let item = menu.items.first(where: { $0.tag == MenuAction.peerCount.rawValue }) else { return }
        let count = discoveryService?.peers.count ?? 0
        item.title = count == 0 ? "No devices nearby" : "\(count) device\(count == 1 ? "" : "s") nearby"
    }

    @discardableResult
    private func sendClipboard(_ text: String) async -> Bool {
        // Same trust-first choice as a file send: clipboard text must not drift
        // to whichever unauthenticated host happens to answer discovery first.
        guard let transfer = transferService, let peer = transfer.defaultTarget() else {
            // A normal local copy should remain quiet when the other machine is
            // asleep or away. Sticky still keeps it in its private history.
            return false
        }
        do {
            try await transfer.sendText(text, to: peer)
            return true
        } catch {
            viewModel.reportClipboardSendError(error.localizedDescription)
            return false
        }
    }

    /// Kept as the single send entry point for the menu, the status-bar drop
    /// area and the Finder service. Recording now happens on the view model's
    /// own success callback, so every path — including a drag straight at the
    /// notch — lands in Recents.
    func sendFilesRecordingRecent(_ urls: [URL]) {
        guard !urls.isEmpty else { return }
        viewModel.sendFiles(urls)
    }


    @objc private func resendRecent(_ sender: NSMenuItem) {
        guard let entry = sender.representedObject as? RecentSend else { return }
        switch entry.payload {
        case .files(let paths):
            let urls = paths.map { URL(fileURLWithPath: $0) }
            // The menu was built a moment ago; a file deleted since then would
            // start a transfer that can only fail.
            guard urls.allSatisfy({ FileManager.default.fileExists(atPath: $0.path) }) else {
                recentsStore.forget(entry)
                return
            }
            sendFilesRecordingRecent(urls)
        case .text(let text):
            Task { @MainActor [weak self] in
                guard let self, await self.sendClipboard(text) else { return }
                self.recentsStore.recordText(text)
            }
        }
    }

    @objc private func handleWake() {
        discoveryService?.announce()
    }

    @objc private func handleScreenChange() {
        notchController?.rebuild()
        installMenuBarItemIfNeeded()
    }

    @objc private func chooseFilesToSend() {
        let picker = NSOpenPanel()
        picker.title = "Send with Sticky"
        picker.prompt = "Send"
        picker.canChooseFiles = true
        picker.canChooseDirectories = true
        picker.allowsMultipleSelection = true
        picker.begin { [weak self] response in
            guard response == .OK else { return }
            self?.sendFilesRecordingRecent(picker.urls)
        }
    }

    @objc private func showShelf() {
        viewModel.showShelf()
    }

    @objc private func sendPendingTransfers() {
        viewModel.processPendingQueue(force: true)
    }

    @objc private func clearPendingTransfers() {
        viewModel.clearPendingTransfers()
    }

    @objc private func sendCopiedText() {
        guard let text = NSPasteboard.general.string(forType: .string), !text.isEmpty else {
            showPairingResult(title: "Nothing to send", message: "Copy some text first, then choose Send copied text.")
            return
        }
        Task { @MainActor [weak self] in
            guard let self, await self.sendClipboard(text) else { return }
            self.recentsStore.recordText(text)
        }
    }

    @objc private func openReceivedFiles() {
        // Same destination the arrival notification's "Open Folder" reveals.
        let folder = ArrivalNotifier.receivedFolder
        try? FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        NSWorkspace.shared.open(folder)
    }

    @objc private func showPairingDialog() {
        guard let transfer = transferService else { return }
        let peers = discoveryService?.peers ?? []
        guard !peers.isEmpty else {
            showPairingResult(title: "No device nearby", message: "Open Sticky on the other computer and make sure both devices are on the same private Wi-Fi.")
            return
        }

        // /api/v1/pair only entertains guesses while a pairing window is open,
        // so the window lives exactly as long as this dialog. `defer` covers
        // every way out — pair, cancel, bad code, vanished device — because a
        // dismissed dialog must not leave the six-digit code guessable from the
        // LAN. Closing it before the pair Task finishes is safe: our outgoing
        // pair is a single request/response to the peer and never needs an
        // inbound /pair of our own.
        transfer.beginPairingWindow()
        defer { transfer.endPairingWindow() }

        let alert = NSAlert()
        alert.messageText = "Pair a Sticky device"
        alert.informativeText = "Enter the six-digit code currently shown on the other computer. The code is only used once to establish trust."
        alert.addButton(withTitle: "Pair")
        alert.addButton(withTitle: "Cancel")

        let accessory = NSStackView()
        accessory.orientation = .vertical
        accessory.alignment = .leading
        accessory.spacing = 8

        let peerPicker = NSPopUpButton(frame: NSRect(x: 0, y: 0, width: 280, height: 28), pullsDown: false)
        // Menu items are built one by one and tagged with the device id: two PCs
        // sharing a display name would otherwise collapse into a single title and
        // pair the user with whichever one happened to be first.
        for peer in peers {
            let item = NSMenuItem(title: "\(peer.name) (\(peer.platform.rawValue))", action: nil, keyEquivalent: "")
            item.representedObject = peer.id
            peerPicker.menu?.addItem(item)
        }
        accessory.addArrangedSubview(peerPicker)

        let codeField = NSSecureTextField(frame: NSRect(x: 0, y: 0, width: 280, height: 28))
        codeField.placeholderString = "Six-digit code"
        codeField.maximumNumberOfLines = 1
        accessory.addArrangedSubview(codeField)
        alert.accessoryView = accessory

        guard alert.runModal() == .alertFirstButtonReturn else { return }
        let code = codeField.stringValue.trimmingCharacters(in: .whitespacesAndNewlines)
        guard code.count == 6, code.allSatisfy(\.isNumber) else {
            showPairingResult(title: "Invalid code", message: "Enter the six digits shown in Sticky on the other computer.")
            return
        }
        guard let selectedID = peerPicker.selectedItem?.representedObject as? String,
              let peer = peers.first(where: { $0.id == selectedID }) else {
            showPairingResult(title: "Device went away", message: "That device is no longer nearby. Try pairing again once it reappears.")
            return
        }
        Task { @MainActor [weak self] in
            do {
                try await transfer.pair(peer: peer, pin: code)
                self?.showPairingResult(title: "Paired", message: "\(peer.name) is now trusted. You can send files and clipboard items normally.")
            } catch {
                self?.showPairingResult(title: "Couldn’t pair", message: error.localizedDescription)
            }
        }
    }

    private func showPairingResult(title: String, message: String) {
        let alert = NSAlert()
        alert.messageText = title
        alert.informativeText = message
        alert.addButton(withTitle: "OK")
        alert.runModal()
    }

    private func forgetPairedDevices() {
        guard let transfer = transferService else { return }
        let alert = NSAlert()
        alert.messageText = "Forget paired devices?"
        alert.informativeText = "Sticky will stop trusting every device on this Mac. You’ll need to pair again before sending or receiving."
        alert.addButton(withTitle: "Forget devices")
        alert.addButton(withTitle: "Cancel")
        guard alert.runModal() == .alertFirstButtonReturn else { return }
        do {
            try transfer.unpairAll()
            showPairingResult(title: "Devices forgotten", message: "Pair again from the Shelf when you’re ready.")
        } catch {
            showPairingResult(title: "Couldn’t forget devices", message: error.localizedDescription)
        }
    }

    @objc private func quit() {
        NSApp.terminate(nil)
    }
}

extension AppDelegate: NSMenuDelegate {
    func menuWillOpen(_ menu: NSMenu) {
        if let codeItem = menu.items.first(where: { $0.tag == MenuAction.pairingCode.rawValue }) {
            codeItem.title = "This Mac's pairing code: \(transferService?.pairingCode ?? "------")"
            // Windows pairs *into* this Mac by typing the code shown on this
            // very menu item, so putting it on screen is the other moment a
            // person is looking at the PIN. Without this, arming the window
            // only in the outgoing dialog would leave the endpoint shut for
            // the inbound half of pairing.
            transferService?.beginPairingWindow()
        }
        refreshPeerCount()
        refreshPendingQueue(in: menu)
        rebuildRecents(in: menu)
    }

    /// Built fresh at open time, torn down with the menu. Recents are a bounded
    /// view of what is true right now, not a shelf that survives on screen.
    private func rebuildRecents(in menu: NSMenu) {
        let stale = menu.items.filter {
            $0.tag == MenuAction.recentsHeader.rawValue || $0.tag == MenuAction.recent.rawValue
        }
        stale.forEach(menu.removeItem)

        let entries = recentsStore.currentEntries()
        guard !entries.isEmpty,
              let anchor = menu.items.firstIndex(where: { $0.tag == MenuAction.openReceived.rawValue })
        else { return }

        var insertionIndex = anchor + 1
        let separator = NSMenuItem.separator()
        separator.tag = MenuAction.recentsHeader.rawValue
        menu.insertItem(separator, at: insertionIndex)
        insertionIndex += 1

        let header = NSMenuItem(title: "Recent", action: nil, keyEquivalent: "")
        header.isEnabled = false
        header.tag = MenuAction.recentsHeader.rawValue
        menu.insertItem(header, at: insertionIndex)
        insertionIndex += 1

        for entry in entries {
            let item = NSMenuItem(title: entry.menuTitle, action: #selector(resendRecent(_:)), keyEquivalent: "")
            item.target = self
            item.tag = MenuAction.recent.rawValue
            item.representedObject = entry
            menu.insertItem(item, at: insertionIndex)
            insertionIndex += 1
        }
    }

    private func refreshPendingQueue(in menu: NSMenu) {
        guard let item = menu.items.first(where: { $0.tag == MenuAction.pendingCount.rawValue }) else { return }
        let count = viewModel.pendingTransfers.reduce(0) { $0 + $1.items.count }
        item.title = count == 0 ? "No pending transfers" : "\(count) item\(count == 1 ? "" : "s") waiting for PC"
        item.isEnabled = count > 0
    }
}

private enum MenuAction: Int {
    case peerCount = 1
    case pairingCode = 2
    case pendingCount = 3
    case openReceived = 4
    case recentsHeader = 5
    case recent = 6
}

final class StatusBarDropArea: NSView {
    var onFilesDropped: (([URL]) -> Void)?

    private var statusButton: NSStatusBarButton? { superview as? NSStatusBarButton }

    override func viewDidMoveToWindow() {
        super.viewDidMoveToWindow()
        registerForDraggedTypes([.fileURL])
    }

    // AppKit picks a drag destination by hit-testing, so this view has to be
    // hit-testable at all times or draggingEntered can never fire. It therefore
    // keeps the default hitTest and hands ordinary clicks straight back to the
    // status-item button underneath, which still opens the menu.
    override func mouseDown(with event: NSEvent) {
        statusButton?.mouseDown(with: event)
    }

    override func rightMouseDown(with event: NSEvent) {
        statusButton?.rightMouseDown(with: event)
    }

    override func otherMouseDown(with event: NSEvent) {
        statusButton?.otherMouseDown(with: event)
    }

    override func draggingEntered(_ sender: NSDraggingInfo) -> NSDragOperation {
        let accepted = sender.draggingPasteboard.canReadObject(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        )
        statusButton?.contentTintColor = accepted ? .stickyAccent : nil
        return accepted ? .copy : []
    }

    override func draggingExited(_ sender: NSDraggingInfo?) {
        statusButton?.contentTintColor = nil
    }

    override func performDragOperation(_ sender: NSDraggingInfo) -> Bool {
        guard let urls = sender.draggingPasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty else { return false }

        onFilesDropped?(urls)
        statusButton?.contentTintColor = nil
        return true
    }

    override func concludeDragOperation(_ sender: NSDraggingInfo?) {
        statusButton?.contentTintColor = nil
    }
}


/// Finder "right-click → Send with Sticky" integration. macOS discovers this
/// through the app's Services menu; the handler accepts any selected files.
@objc final class ServicesProvider: NSObject {
    @objc func sendFilesFromFinder(_ pasteboard: NSPasteboard, userData: String?, error: AutoreleasingUnsafeMutablePointer<NSString>) {
        let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                          options: [.urlReadingFileURLsOnly: true]) as? [URL] ?? []
        guard !urls.isEmpty else { return }
        Task { @MainActor in
            // Routed through the delegate rather than straight at the view
            // model so a send started from Finder lands in Recents like any
            // other; the view model stays the fallback if the delegate is gone.
            if let delegate = NSApp.delegate as? AppDelegate {
                delegate.sendFilesRecordingRecent(urls)
            } else {
                AppDelegate.sharedViewModel?.sendFiles(urls)
            }
        }
    }
}
